In [1]:
import numpy as np

In [2]:
arr = np.arange(16).reshape(4, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [3]:
# 배열 정보 확인
arr.shape

(4, 4)

In [4]:
arr.dtype

dtype('int32')

In [5]:
arr_zeros = np.zeros((3, 4))
arr_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
# 사칙연산
arr1 = np.array([[1,2,3], [4,5,6]], dtype=np.float64)
arr2 = np.array([[7,8,9], [0,1,2]], dtype=np.float64)

In [7]:
print("arr1 + arr2 = ")
print(arr1 + arr2, "\n")
print("arr1 - arr2 = ")
print(arr1 - arr2, "\n")
print("arr1 * arr2 = ")
print(arr1 * arr2, "\n")
print("arr1 / arr2 = ")
print(arr1 / arr2, "\n")

arr1 + arr2 = 
[[ 8. 10. 12.]
 [ 4.  6.  8.]] 

arr1 - arr2 = 
[[-6. -6. -6.]
 [ 4.  4.  4.]] 

arr1 * arr2 = 
[[ 7. 16. 27.]
 [ 0.  5. 12.]] 

arr1 / arr2 = 
[[0.14285714 0.25       0.33333333]
 [       inf 5.         3.        ]] 



C:\Users\jinw0\AppData\Local\Temp\ipykernel_2100\2500981473.py:8: RuntimeWarning: divide by zero encountered in true_divide
  print(arr1 / arr2, "\n")
